name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get -y install build-essential

    - name: Download and install criterion
      run: |
        git clone --branch v3.1.3 --depth 1 https://github.com/Snaipe/Criterion.git
        cd Criterion
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    - name: configure
      run: make clean all -C . && echo "build done"
    - name: test
      run: bin/${EXEC}_tests -S --verbose=0 --timeout 30

